Repository Ph3nol/NotificationPusher, pull requests merged in 2020-05, with the labels that each got.

#192 Add support to pass priority argument to GCM
  src/Sly/NotificationPusher/Adapter/Gcm.php
Labels: 2.x, enhancement

#193 Remove check on token length as this can vary
  src/Sly/NotificationPusher/Adapter/Apns.php
Labels: 2.x, bug, code-review

#195 clean up code a bit, add php 7.3 and 7.4 to travis, fix deps a bit
  .travis.yml
  README.md
  composer.json
  composer.lock
  docker-compose.yml
  docker/php-cli/Dockerfile
  src/Sly/NotificationPusher/AbstractPushService.php
  src/Sly/NotificationPusher/Adapter/AdapterInterface.php
  src/Sly/NotificationPusher/Adapter/Apns.php
  src/Sly/NotificationPusher/Adapter/ApnsAPI.php
  src/Sly/NotificationPusher/Adapter/BaseAdapter.php
  src/Sly/NotificationPusher/Adapter/FeedbackAdapterInterface.php
  src/Sly/NotificationPusher/Adapter/Gcm.php
  src/Sly/NotificationPusher/ApnsPushService.php
  src/Sly/NotificationPusher/Collection/AbstractCollection.php
  src/Sly/NotificationPusher/Collection/DeviceCollection.php
  src/Sly/NotificationPusher/Collection/MessageCollection.php
  src/Sly/NotificationPusher/Collection/PushCollection.php
  src/Sly/NotificationPusher/Collection/ResponseCollection.php
  src/Sly/NotificationPusher/Console/Application.php
  src/Sly/NotificationPusher/Console/Command/PushCommand.php
  src/Sly/NotificationPusher/Exception/AdapterException.php
  src/Sly/NotificationPusher/Exception/ExceptionInterface.php
  src/Sly/NotificationPusher/Exception/InvalidException.php
  src/Sly/NotificationPusher/Exception/PushException.php
  src/Sly/NotificationPusher/Exception/RuntimeException.php
  src/Sly/NotificationPusher/GcmPushService.php
  src/Sly/NotificationPusher/Model/BaseOptionedModel.php
  src/Sly/NotificationPusher/Model/BaseParameteredModel.php
  src/Sly/NotificationPusher/Model/Device.php
  src/Sly/NotificationPusher/Model/DeviceInterface.php
  src/Sly/NotificationPusher/Model/Message.php
  src/Sly/NotificationPusher/Model/MessageInterface.php
  src/Sly/NotificationPusher/Model/Push.php
  src/Sly/NotificationPusher/Model/PushInterface.php
  src/Sly/NotificationPusher/Model/Response.php
  src/Sly/NotificationPusher/Model/ResponseInterface.php
  src/Sly/NotificationPusher/NotificationPusher.php
  src/Sly/NotificationPusher/PushManager.php
  tests/units/Sly/NotificationPusher/Adapter/Apns.php
  tests/units/Sly/NotificationPusher/Adapter/BaseAdapter.php
  tests/units/Sly/NotificationPusher/Adapter/Gcm.php
  tests/units/Sly/NotificationPusher/Model/BaseOptionedModel.php
  tests/units/Sly/NotificationPusher/Model/BaseParameteredModel.php
  tests/units/Sly/NotificationPusher/Model/Device.php
  tests/units/Sly/NotificationPusher/Model/Message.php
  tests/units/Sly/NotificationPusher/Model/Push.php
  tests/units/Sly/NotificationPusher/PushManager.php
Labels: 2.x, code-review, enhancement
